### ISSUE TITLE
A few questions (mostly about CSS)

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/pretty-products#1]
I'm almost done with this exercise but struggling in a few areas and would appreciate some help:

- The box height… you can see that the adjacent `<li>` elements (products) are not aligned; one is shorter than the other and the difference changes with browser width. I tried applying *width* and *flex-grow* (following video instructions) but it didn’t help;

- How can I layout the box elements at the bottom as in screenshot (“Add to cart” to left and the other two icons to right) ? I tried few things including putting left and right in two `<span>` tags thinking it’d be easy to manipulate them, then applied different flexbox properties but no luck;

- There are two *corner-radii* values provided (3em, 6px). One is for the boxes (products); what’s the other one for? "Add to cart"? (Currently there is no *border* applied to that element though, just *background-colour*);

- A bit confused about text sizes 1.4rem and 2rem… wondering if they are for `<p>` and `<h2>` (considering there’s no `<h1>` on the page yet)? ... but then the outcome looks quite different than the screenshot;

- A warning by HTML Validator suggests that the *role="main"* is unnecessary for `<main>` element… is this one of Validator’s invalid and quirky warnings that I should avoid?

@thomasjbradley

<img width="967" alt="Screen Shot 2021-03-02 at 10 18 56 PM" src="https://user-images.githubusercontent.com/16348315/110188729-bd7f7c00-7dea-11eb-8723-7d33d6fb8178.png">

**Comment by thomasjbradley** [comment]
*card heights—*

Remove `align-items: center` from the `grid` and they’ll stretch to the same height.

*button alignment—*

You have the right idea with `justify-content`. The problem is just that the `<p>` tag isn’t wide enough. Try adding `width: 100%` on it and that should help.

*border-radius—*

On the border around the cards, like you have. And on the “Add to cart” buttons, also like you have.

*font-sizes—*

Yep: `<h2>` & `<p>`

*validator warning—*

Yes, I would ignore that warning. Though it’s true that `role="main"` isn’t necessary on the `<main>` tag, we’re trying to just be more compatible. Many accessibility tools supported `role` before `<main>`, therefore we can capture support on older devices too.

**Comment by C-G-G** [comment]
Thank you! Both major issues (card heights and button alignment) are fixed.
